feat: Add file transfer on save (TT-1255)
NationalLibraryOfNorway/trokk pull request #14
Opened 2023-12-07 10:51 UTC by MariusLevang

2023-12-07 14:39 UTC, Sindrir requested changes
Ellers, så er det kanskje på tide å åpne opp rettighetene fil fs? Altså ikke bare "$documents/trokk". 

Vet ikke om scannermaskinene er standarisert nok til at vi kan sette faste stier der.

2023-12-07 14:39 UTC, Sindrir commented on src/lib/RegistrationSchema.svelte
> +        }
Burde vi ikke flytte filene før vi poster til server? Så vet vi filene er klare.

2023-12-08 06:14 UTC, MariusLevang commented
> Ellers, så er det kanskje på tide å åpne opp rettighetene fil fs? Altså ikke bare "$documents/trokk".
> 
> Vet ikke om scannermaskinene er standarisert nok til at vi kan sette faste stier der.

Da må vi vell fort åpne tilgang for alle filer siden vi ikke har peilng på hvilke disker osv. Blir vell fort det vi må uansett. Så da er spørsmålet om vi skal ta det her eller i en egen sak.

2023-12-08 06:31 UTC, MariusLevang commented on src/lib/RegistrationSchema.svelte
> +        }
Alternativt kan vi generere UUID allerede i Trøkk og sende denne med til PAPI.

2023-12-08 09:30 UTC, MariusLevang commented on src-tauri/src/main.rs
> +			convert_to_webp,
Woops, fikset.

2023-12-08 09:32 UTC, Sindrir approved these changes

2023-12-08 09:32 UTC, merged