refactor: Refactor and improve login (TT-1305)
NationalLibraryOfNorway/trokk pull request #27
Opened 2024-01-24 14:23 UTC by MariusLevang

Moved to separate file for easier access across components, and added tests.

2024-01-29 12:13 UTC, Sindrir requested changes

2024-01-29 12:13 UTC, Sindrir commented on src/lib/Auth.svelte
> +                settings.authResponse = event.payload as AuthenticationResponse
Burde vel sette refreshTokenIntervallet etter vi har satt authresponsen her? Den brukes jo i setRefreshAccessTokenInterval

2024-01-29 12:13 UTC, Sindrir commented on src/lib/Auth.svelte
> +                    setRefreshAccessTokenInterval()
Setter vi nytt interval for hver gang vi refresher så bygger vi opp at det skal kjøre mer og mer requests. Så den vil vi nok bare kalle en gang. Enten ved login eller ved første automatiske refresh på oppstart.

2024-01-29 14:15 UTC, MariusLevang commented on src/App.svelte
> +      await appWindow.listen('token_exchanged', (event) => {
`login()` returnerer før "token_exchanged"-event er sendt, lyttes bare på i ettertid for responsen. Så en `await settings.authResponse` vil returnere null eller objektet fra forrige login med en gang. 

Har prøvd litt signals og greier for å sende fra `Auth.svelte` uten å måtte lytte til eventen, men fungerer ikke når det er en `context="module"`-komponent. Siste commit gjør første-login/refresh i `Auth.svelte` som en vanlig komponent, og heller deler authResponse med `App.svelte`.

2024-02-13 15:26 UTC, Sindrir approved these changes

2024-02-13 15:26 UTC, merged