feat: Add logout button (TT-1429)
NationalLibraryOfNorway/trokk pull request #34
Opened 2024-02-19 15:20 UTC by Sindrir

2024-02-20 06:48 UTC, fredrikmonsen reviewed
La til et par n-er

2024-02-20 06:48 UTC, fredrikmonsen commented on src/App.svelte
> +        <button on:click={() => openSettings = !openSettings} >Instillinger</button>
```suggestion
        <button on:click={() => openSettings = !openSettings} >Innstillinger</button>
```

2024-02-20 06:48 UTC, fredrikmonsen commented on src/App.svelte
> +        <button on:click={() => authComponent.login()}>Logg in</button>
```suggestion
        <button on:click={() => authComponent.login()}>Logg inn</button>
```
Litt norwenglish her

2024-02-20 06:55 UTC, MariusLevang requested changes

2024-02-20 06:55 UTC, MariusLevang commented on src/lib/Auth.svelte
> +            loggedOut = false;
Burde ikke denne settes til false etter vi har fått token_exchanged eventen? Ser for meg at noen ikke får logget seg inn og lukker login-vinduet, og pr. nå må de da restarte trøkk.

Ser at det samme skjer hvis man lukker login-vinduet første gangen etter åpning av trøkk, så det er kanskje en helhetlig ting vi skulle sett på. Egen sak?

2024-02-20 06:55 UTC, MariusLevang commented on src/App.svelte
> +        <button on:click={() => authComponent.login()}>Logg in</button>
```suggestion
        <button on:click={() => authComponent.login()}>Logg inn</button>
```

2024-02-21 07:50 UTC, MariusLevang commented
@Sindrir ser bra ut nå om du var ferdig

2024-02-21 07:50 UTC, MariusLevang approved these changes

2024-03-05 09:20 UTC, fredrikmonsen commented on vite.config.ts
> +      : null),*/
fjern

2024-03-05 09:36 UTC, fredrikmonsen approved these changes

2024-03-05 09:52 UTC, merged