feat: create detailed image view (TT-1782)
NationalLibraryOfNorway/trokk pull request #51
Opened 2024-12-16 14:41 UTC by fredrikmonsen

2024-12-20 15:07 UTC, Sindrir requested changes

2024-12-20 15:07 UTC, Sindrir commented on src-tauri/src/image_converter.rs
> +		if check_if_preview_exists(&file)? {
Regner med en refaktoreringsfeil, revert.

2025-01-13 09:08 UTC, Sindrir commented on src/features/files-container/files-container.tsx
> +                            !(child.name.startsWith('.thumbnails') || child.name.startsWith('.previews')) && child.isDirectory ? (
Vi ønsker å vise preview mappen?

2025-01-16 11:56 UTC, fredrikmonsen commented on src/features/files-container/files-container.tsx
> +                            !(child.name.startsWith('.thumbnails') || child.name.startsWith('.previews')) && child.isDirectory ? (
Negasjonen ! omfavner begge her. Eller tenker du at vi skal vise mappa?

2025-01-16 11:57 UTC, fredrikmonsen commented on src/features/detailed-image-view/detailed-image-view.tsx
> +    };
La til kommentarer med eksempler

2025-01-16 14:43 UTC, merged