feat: Add login via OICD provider
NationalLibraryOfNorway/trokk pull request #6
Opened 2023-11-20 11:58 UTC by Sindrir

2023-11-21 08:03 UTC, MariusLevang requested changes
Et spørsmål og en gjennomgående typo

2023-11-21 08:03 UTC, MariusLevang commented on src-tauri/src/main.rs
> +        oicd_client_secret: env!("OICD_CLIENT_SECRET").parse().unwrap(),
Er vell "OIDC", ikke "OICD" (**O**pen**ID C**onnect)

2023-11-21 08:03 UTC, MariusLevang commented on src/lib/model/required-env-variables.ts
> +    oicdClientSecret: string;
OIDC

2023-11-21 15:30 UTC, Sindrir commented on src-tauri/src/main.rs
> +                    redirect_url.pop(); // remove trailing '/'
La inn en sjekk på dette før vi popper

2023-11-22 06:37 UTC, MariusLevang requested changes
Fant en til typo i en kommentar, bare fikser den, ellers meget good!

... men får det ikke til å fungere lokalt.

2023-11-22 06:37 UTC, MariusLevang commented on src-tauri/src/model.rs
> +    #[serde(rename(serialize = "notBeforePolicy", deserialize = "not-before-policy"))] // NB! Special kebab-case from OICD-server
```suggestion
    #[serde(rename(serialize = "notBeforePolicy", deserialize = "not-before-policy"))] // NB! Special kebab-case from OIDC-server
```

2023-11-22 06:38 UTC, MariusLevang approved these changes

2023-11-22 08:02 UTC, merged